### ISSUE TITLE
Errors in dashboard

### ISSUE THREAD

**Issue by jothoma1** [allangood/grafana#1]
Hi, i have tried to import your dashboard in my grafana but there is some errors :

- On all widget there is a group by time($___interval) it doesnt work it should be time($interval). And i dont understand why you use this ? In grafana you can select the interval natively.

Another thing, maybe we can add a templating variable in order to select only the hosts that are Graylog servers ? In my grafana setup i have hundreds of hosts and it's a bit confusing that the host variable display all hosts. I have modified with : 

> SHOW TAG VALUES FROM "org.graylog2.throughput.input.1-sec-rate" WITH KEY = "host"

Thanks a lot for your work !
Johan

**Comment by allangood** [comment]
Hi Johan,

I updated the dahsboard, and now is showing only graylog servers.
I'm using this $interval from template because, for me at least, sometimes is important to override the default time interval when you have a big interval, like two or more days. With this option, is possible to get a more precise graph even on a big time range.

Regards.
